from Tecnico import Tecnico
from Maestro import Maestro

tecnico1 = Tecnico()
tecnico1.setNombres(input("Ingrese Nombre del Tecnico: "))
tecnico1.setApellidos(input("Ingrese Apellido: "))
tecnico1.setTelefono(int(input("Ingrese Telefono: ")))
tecnico1.setDirec(input("Ingrese Dirección: "))
tecnico1.setGenero(input("Ingrese Género: "))
tecnico1.setProfe(input("Ingrese Profesión: "))
tecnico1.setUsuario(input("Ingrese Usuario: "))
tecnico1.setContraseña(input("Ingrese Contraseña: "))
tecnico1.setEspecialidad(input("Ingrese especialización: "))
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Datos del Tëcnico: ")
print("Nombre: ",tecnico1.getNombres())
print("Apellido: ", tecnico1.getApellidos())
print("Telefono: ", tecnico1.getTelefono())
print("Dirección: ", tecnico1.getDirec())
print("Género: ", tecnico1.getGenero())
print("Profesión: ",tecnico1.getProfe())
print("Usuario: ", tecnico1.getUsuario())
print("Contraseña: ",tecnico1.getContraseña())
print("Especialidad: ",tecnico1.getEspecialidad())
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Ingrese los datos del Maestro: ")
maestro1 = Maestro()
maestro1.setNombres(input("Ingrese Nombre: "))
maestro1.setApellidos(input("Ingrese Apellido: "))
maestro1.setTelefono(int(input("Ingrese Telefono: ")))
maestro1.setDirec(input("Ingrese Dirección: "))
maestro1.setGenero(input("Ingrese Género: "))
maestro1.setProfe(input("Ingrese Profesión: "))
maestro1.setUsuario(input("Ingrese Usuario: "))
maestro1.setContraseña(input("Contraseña: "))
print("---------------------------------------------------------------")
print("---------------------------------------------------------------")

print("Datos del Maestro: ")
print("Nombre: ",maestro1.getNombres())
print("Apellido: ", maestro1.getApellidos())
print("Telefono: ", maestro1.getTelefono())
print("Dirección: ", maestro1.getDirec())
print("Género: ", maestro1.getGenero())
print("Profesión: ",maestro1.getProfe())
print("Usuario: ", maestro1.getUsuario())
print("Contraseña: ",maestro1.getContraseña())